#!/bin/bash
# Helper script to check and copy QSys generated files.
#
# This script is called by `FPGA/Makefile` to:
# - Reuse existing generated artifacts when available
# - Generate QSys HDL/sopcinfo when missing
# - Copy generated outputs into the GUI-visible directory for Platform Designer compatibility
# - Overlay custom IP source files onto generated submodules (ip/custom/ is canonical)

set -euo pipefail

QSYS_FILE="$1"
QSYS_DIR="$2"
GENERATED_DIR="$3"
QSYS_BASE="$4"
QSYS_STAMP="$5"
QSYS_SOPCINFO="$6"
QSYS_GENERATE_CMD="${7:-qsys-generate}"
# Arg 8: space-separated custom IP directories (auto-discovered by Makefile)
IP_SEARCH_PATHS="${8:-}"

# qsys-generate creates a synthesis/ subdirectory automatically, so output to parent
generatedOutputDir="$GENERATED_DIR/$QSYS_BASE"
generatedSynthesisDir="$generatedOutputDir/synthesis"
generatedSopcinfo1="$GENERATED_DIR/$QSYS_BASE/$QSYS_BASE.sopcinfo"
generatedSopcinfo2="$generatedSynthesisDir/$QSYS_BASE.sopcinfo"
guiDir="$QSYS_DIR/$QSYS_BASE"
guiSynthesisDir="$guiDir/synthesis"
guiSopcinfo="$guiDir/$QSYS_BASE.sopcinfo"

ensure_stamp() {
	mkdir -p "$(dirname "$QSYS_STAMP")"
	touch "$QSYS_STAMP"
}

# Overlay ip/custom/ source files onto the generated submodules directory.
# QSys regeneration always overwrites submodules with template stubs.
# This ensures our fixes (combinatorial reads, IEEE 754 normalization, etc.)
# survive QSys regeneration — ip/custom/ is the canonical source of truth.
#
# Iterates over ALL custom IP directories (not just one hardcoded path).
overlay_custom_ip() {
	local submodules_dir="$guiSynthesisDir/submodules"
	local gen_submodules_dir="$generatedSynthesisDir/submodules"
	local overlaid=0

	for ip_dir in $IP_SEARCH_PATHS; do
		[ -d "$ip_dir" ] || continue
		for f in "$ip_dir"/*.v; do
			[ -f "$f" ] || continue
			base="$(basename "$f")"
			[ -f "$submodules_dir/$base" ] && cp "$f" "$submodules_dir/$base" && overlaid=1
			[ -f "$gen_submodules_dir/$base" ] && cp "$f" "$gen_submodules_dir/$base" && overlaid=1
		done
	done

	if [ "$overlaid" -eq 1 ]; then
		echo "Overlaid ip/custom/ source files onto submodules"
	fi
}

# Build the --search-path argument for qsys-generate from all custom IP directories.
# Format: --search-path=/path/to/ip1,/path/to/ip2,...,$
build_search_path_arg() {
	if [ -z "$IP_SEARCH_PATHS" ]; then
		echo ""
		return
	fi
	local paths=""
	for ip_dir in $IP_SEARCH_PATHS; do
		[ -d "$ip_dir" ] || continue
		if [ -z "$paths" ]; then
			paths="$ip_dir"
		else
			paths="$paths,$ip_dir"
		fi
	done
	if [ -n "$paths" ]; then
		echo "--search-path=$paths,\$"
	fi
}

copy_sopcinfo_if_present() {
	if [ -f "$generatedSopcinfo1" ]; then
		cp "$generatedSopcinfo1" "$QSYS_SOPCINFO"
	elif [ -f "$generatedSopcinfo2" ]; then
		cp "$generatedSopcinfo2" "$QSYS_SOPCINFO"
	fi
}

# Case 1: Already have the "expected" Makefile outputs.
if [ -f "$QSYS_SOPCINFO" ] && [ -f "$generatedSynthesisDir/$QSYS_BASE.qip" ]; then
	# Check if source is newer than generated files (needs regeneration)
	if [ "$QSYS_FILE" -nt "$QSYS_SOPCINFO" ] || [ "$QSYS_FILE" -nt "$generatedSynthesisDir/$QSYS_BASE.qip" ]; then
		echo "QSys source file is newer than generated files. Regenerating..."
	else
		echo "QSys files already exist and are up-to-date in $GENERATED_DIR/$QSYS_BASE/"
		echo "Copying to GUI location ($guiDir/) for GUI compatibility..."
		mkdir -p "$guiDir"
		if [ -d "$generatedSynthesisDir" ]; then
			cp -r "$generatedSynthesisDir" "$guiDir/" 2>/dev/null || true
		fi
		if [ -f "$QSYS_SOPCINFO" ] && [ ! -f "$guiSopcinfo" ]; then
			cp "$QSYS_SOPCINFO" "$guiSopcinfo" 2>/dev/null || true
		fi
		overlay_custom_ip
		echo "Skipping generation (using existing files)"
		ensure_stamp
		exit 0
	fi
fi

# Case 2: Have GUI-generated outputs; copy them to the Makefile-generated directory.
if [ -d "$guiSynthesisDir" ] && [ -f "$guiSynthesisDir/$QSYS_BASE.qip" ]; then
	# Check if source is newer than GUI-generated files
	if [ "$QSYS_FILE" -nt "$guiSynthesisDir/$QSYS_BASE.qip" ]; then
		echo "QSys source file is newer than GUI-generated files. Regenerating..."
	else
		echo "Found QSys files generated by Platform Designer GUI in $guiDir/"
		echo "Copying to $GENERATED_DIR/$QSYS_BASE/..."
		mkdir -p "$GENERATED_DIR/$QSYS_BASE"
		cp -r "$guiSynthesisDir" "$GENERATED_DIR/$QSYS_BASE/"
		if [ -f "$guiSopcinfo" ]; then
			cp "$guiSopcinfo" "$QSYS_SOPCINFO"
		else
			copy_sopcinfo_if_present
		fi
		overlay_custom_ip
		echo "Files copied successfully"
		echo "QSys generation complete (using GUI-generated files)"
		ensure_stamp
		exit 0
	fi
fi

# Case 3: Need to generate using qsys-generate.
echo "Generating QSys system: $QSYS_FILE"
echo "Output directory: $GENERATED_DIR"

if ! command -v "$QSYS_GENERATE_CMD" >/dev/null 2>&1 && [ ! -f "$QSYS_GENERATE_CMD" ]; then
	echo ""
	echo "ERROR: qsys-generate command not found"
	echo "  Tried: $QSYS_GENERATE_CMD"
	echo "Quartus Prime tools are required for QSys generation."
	echo ""
	echo "Install Quartus Prime and ensure the Quartus bin directory is on PATH."
	exit 1
fi

echo "This may take several minutes..."
mkdir -p "$generatedOutputDir"

# Build search path from all discovered custom IP directories
SEARCH_PATH_ARG="$(build_search_path_arg)"
if [ -n "$SEARCH_PATH_ARG" ]; then
	echo "Custom IP search paths: $SEARCH_PATH_ARG"
fi

# Generate to a temp directory first, then copy to final location.
# On Docker Desktop (macOS), bind-mounted /workspace can silently drop files
# during bulk writes. Generating to /tmp (overlay FS) avoids this issue.
QSYS_TEMP_DIR="/tmp/qsys-generate-$$"
mkdir -p "$QSYS_TEMP_DIR"

"$QSYS_GENERATE_CMD" "$QSYS_FILE" --synthesis=VERILOG --output-directory="$QSYS_TEMP_DIR" $SEARCH_PATH_ARG || {
	echo ""
	echo "WARNING: QSys generation completed with errors (this may be non-critical)."
	echo "Checking if critical files were generated..."
	if [ -f "$QSYS_TEMP_DIR/synthesis/$QSYS_BASE.qip" ]; then
		echo "Critical QIP found - Quartus compilation may still work."
	else
		echo "ERROR: Critical files missing. Ensure Quartus Prime is properly installed."
		rm -rf "$QSYS_TEMP_DIR"
		exit 1
	fi
}

# Copy from temp to final workspace location
echo "Copying generated files to workspace..."
cp -r "$QSYS_TEMP_DIR"/* "$generatedOutputDir"/
rm -rf "$QSYS_TEMP_DIR"

copy_sopcinfo_if_present

# Copy generated files to GUI location for GUI compatibility
if [ -d "$generatedSynthesisDir" ]; then
	echo "Copying generated files to GUI location ($guiDir/) for GUI compatibility..."
	mkdir -p "$guiDir"
	cp -r "$generatedSynthesisDir" "$guiDir/" 2>/dev/null || true
	if [ -f "$QSYS_SOPCINFO" ] && [ ! -f "$guiSopcinfo" ]; then
		cp "$QSYS_SOPCINFO" "$guiSopcinfo" 2>/dev/null || true
	fi
fi

# After any fresh generation, overlay ip/custom/ to fix QSys stub overwrite
overlay_custom_ip

ensure_stamp
